#!/usr/bin/env python3
"""
gpx2obj.py -- превращает GPX-трек в Wavefront OBJ.

Два режима:
  --mode waypoints  -> вершины в точках центра дороги (элементы `p`, опционально ломаная `l`)
  --mode road       -> непрерывный меш дороги (лента с общими вершинами), машина едет
                       по центру. Ширина --width на прямых, в крутых поворотах плавно
                       растёт до --width-max (уширение проезжей части в кривых).
                       С --rects: старый вариант, независимые прямоугольники на отрезок.

Система координат:
  * центр (--lat0/--lon0) -> начало координат;
  * земля плоская: метров на градус широты/долготы считается один раз по широте центра;
  * OBJ: X = восток, Y = вверх (высота), Z = юг (правая тройка, Y-up).
    С флагом --z-up: X = восток, Y = север, Z = вверх.

Только стандартная библиотека.
"""

import argparse
import math
import os
import sys
import xml.etree.ElementTree as ET

LAT0 = 44.695970867268315
LON0 = 20.501830006042887
WIDTH = 3.5          # ширина на прямой, м
WIDTH_MAX = 5.0      # ширина в самом крутом повороте, м
R_NARROW = 120.0     # радиус, начиная с которого уширения нет, м
R_WIDE = 20.0        # радиус, при котором достигается WIDTH_MAX, м
STEP = 1.0           # шаг пересэмплирования трека, м
SMOOTH = 6.0         # окно сглаживания геометрии, м
CURV_SPAN = 12.0     # плечо для оценки радиуса кривизны, м
WIDTH_SMOOTH = 25.0  # окно сглаживания ширины (длина отгона уширения), м
SMOOTH_Z = 20.0      # окно сглаживания высоты, м
JUMP = 3.0           # порог бокового/обратного скачка GNSS, м
JUMP_Z = 2.5         # порог скачка по высоте, м
JUMP_BLEND = 40.0    # длина, на которой боковой скачок плавно сшивается, м
JUMP_BLEND_Z = 100.0 # то же для скачка высоты, м
GLITCH = 60.0        # два противоположных скачка ближе этого -> вырезать кусок между ними, м
MAX_GRADE = 0.15     # максимально правдоподобный уклон дороги (для детектора скачков высоты)


# --------------------------------------------------------------------------- #
# GPX
# --------------------------------------------------------------------------- #

def read_gpx(path):
    """Возвращает список (lat, lon, ele) по всем trkpt всех треков/сегментов."""
    tree = ET.parse(path)
    root = tree.getroot()
    pts = []
    for trkpt in root.iter():
        tag = trkpt.tag.rsplit('}', 1)[-1]
        if tag != 'trkpt':
            continue
        lat = float(trkpt.attrib['lat'])
        lon = float(trkpt.attrib['lon'])
        ele = 0.0
        for child in trkpt:
            if child.tag.rsplit('}', 1)[-1] == 'ele' and child.text:
                ele = float(child.text)
                break
        pts.append((lat, lon, ele))
    return pts


# --------------------------------------------------------------------------- #
# Проекция "плоская земля"
# --------------------------------------------------------------------------- #

def meters_per_degree(lat_deg):
    """Метров в градусе широты и долготы на данной широте (WGS84, ряд)."""
    phi = math.radians(lat_deg)
    m_lat = (111132.954
             - 559.822 * math.cos(2 * phi)
             + 1.175 * math.cos(4 * phi))
    m_lon = (111412.84 * math.cos(phi)
             - 93.5 * math.cos(3 * phi)
             + 0.118 * math.cos(5 * phi))
    return m_lat, m_lon


class FlatProjection:
    def __init__(self, lat0, lon0, ele_offset=0.0):
        self.lat0 = lat0
        self.lon0 = lon0
        self.ele_offset = ele_offset
        self.m_lat, self.m_lon = meters_per_degree(lat0)

    def to_enu(self, lat, lon, ele):
        """-> (east, north, up) в метрах."""
        e = (lon - self.lon0) * self.m_lon
        n = (lat - self.lat0) * self.m_lat
        u = ele - self.ele_offset
        return e, n, u


def enu_to_obj(e, n, u, z_up):
    if z_up:
        return e, n, u          # X=восток, Y=север, Z=вверх
    return e, u, -n             # X=восток, Y=вверх, Z=юг


def dedupe(enu_pts, min_step):
    """Убирает подряд идущие точки ближе min_step (в горизонтальной плоскости)."""
    if min_step <= 0 or not enu_pts:
        return list(enu_pts)
    out = [enu_pts[0]]
    for p in enu_pts[1:]:
        q = out[-1]
        if math.hypot(p[0] - q[0], p[1] - q[1]) >= min_step:
            out.append(p)
    return out


# --------------------------------------------------------------------------- #
# Генерация OBJ
# --------------------------------------------------------------------------- #

def fmt(x):
    return '%.4f' % x


def write_header(f, src, mode, proj, args, n_src, n_used):
    f.write('# generated by gpx2obj.py\n')
    f.write('# source: %s\n' % os.path.basename(src))
    f.write('# mode: %s\n' % mode)
    f.write('# origin: lat=%.12f lon=%.12f ele_offset=%.3f\n'
            % (proj.lat0, proj.lon0, proj.ele_offset))
    f.write('# flat earth: %.4f m/deg lat, %.4f m/deg lon\n' % (proj.m_lat, proj.m_lon))
    if args.z_up:
        f.write('# axes: X=east Y=north Z=up\n')
    else:
        f.write('# axes: X=east Y=up Z=south\n')
    f.write('# trkpt in source: %d, used: %d (min-step %.3f m)\n'
            % (n_src, n_used, args.min_step))
    if mode == 'road':
        if args.rects:
            f.write('# road: independent rectangles, width %.2f m\n' % args.width)
        else:
            f.write('# road: continuous strip, width %.2f m (R>=%.0f m) .. %.2f m (R<=%.0f m), '
                    'step %.2f m, smooth %.1f/%.1f m, curv-span %.1f m, width-smooth %.1f m, '
                    'jump %.1f/%.1f m blend %.0f/%.0f m glitch %.0f m\n'
                    % (args.width, args.r_narrow, args.width_max, args.r_wide,
                       args.step, args.smooth, args.smooth_z, args.curv_span, args.width_smooth,
                       args.jump, args.jump_z, args.jump_blend, args.jump_blend_z, args.glitch))


def write_waypoints(f, pts, z_up, polyline):
    f.write('o waypoints\n')
    for e, n, u in pts:
        x, y, z = enu_to_obj(e, n, u, z_up)
        f.write('v %s %s %s\n' % (fmt(x), fmt(y), fmt(z)))
    for i in range(1, len(pts) + 1):
        f.write('p %d\n' % i)
    if polyline and len(pts) > 1:
        f.write('l ' + ' '.join(str(i) for i in range(1, len(pts) + 1)) + '\n')


def write_road_rects(f, pts, width, z_up):
    """Независимый прямоугольник на каждый отрезок трека (4 вершины, 1 квад)."""
    half = width / 2.0
    f.write('o road\n')
    n_faces = 0
    for (e0, n0, u0), (e1, n1, u1) in zip(pts, pts[1:]):
        de, dn = e1 - e0, n1 - n0
        L = math.hypot(de, dn)
        if L == 0.0:
            continue
        # перпендикуляр влево по ходу движения (в горизонтальной плоскости)
        le, ln = -dn / L * half, de / L * half
        corners = [
            (e0 + le, n0 + ln, u0),   # начало, лево
            (e0 - le, n0 - ln, u0),   # начало, право
            (e1 - le, n1 - ln, u1),   # конец, право
            (e1 + le, n1 + ln, u1),   # конец, лево
        ]
        base = 4 * n_faces
        for e, n, u in corners:
            x, y, z = enu_to_obj(e, n, u, z_up)
            f.write('v %s %s %s\n' % (fmt(x), fmt(y), fmt(z)))
        # порядок: против часовой при взгляде сверху -> нормаль вверх
        f.write('f %d %d %d %d\n' % (base + 1, base + 2, base + 3, base + 4))
        n_faces += 1
    return n_faces


def resample(pts, step):
    """Пересэмплирование ломаной по длине дуги с шагом step (линейная интерполяция)."""
    if step <= 0 or len(pts) < 2:
        return list(pts)
    out = [pts[0]]
    carry = 0.0          # сколько ещё пройти до следующей выдачи
    for p, q in zip(pts, pts[1:]):
        seg = math.hypot(q[0] - p[0], q[1] - p[1])
        if seg == 0.0:
            continue
        pos = step - carry
        while pos <= seg:
            t = pos / seg
            out.append(tuple(p[k] + (q[k] - p[k]) * t for k in range(3)))
            pos += step
        carry = seg - (pos - step)
    if out[-1] != pts[-1]:
        out.append(pts[-1])
    return out


def moving_average(values, window):
    """Центрированное скользящее среднее по списку кортежей/чисел, окно в отсчётах."""
    n = len(values)
    if window <= 1 or n == 0:
        return list(values)
    half = window // 2
    scalar = not isinstance(values[0], tuple)
    vals = [(v,) for v in values] if scalar else values
    dim = len(vals[0])
    # префиксные суммы
    pref = [[0.0] * dim]
    for v in vals:
        pref.append([pref[-1][k] + v[k] for k in range(dim)])
    out = []
    for i in range(n):
        a = max(0, i - half)
        b = min(n, i + half + 1)
        avg = tuple((pref[b][k] - pref[a][k]) / (b - a) for k in range(dim))
        out.append(avg[0] if scalar else avg)
    return out


def curvatures(pts, span_samples):
    """Кривизна (1/R) в каждой точке по окружности через точки i-d, i, i+d."""
    n = len(pts)
    d = max(1, span_samples)
    out = [0.0] * n
    for i in range(n):
        a = pts[max(0, i - d)]
        b = pts[i]
        c = pts[min(n - 1, i + d)]
        if a is b or c is b:
            continue
        ab = math.hypot(b[0] - a[0], b[1] - a[1])
        bc = math.hypot(c[0] - b[0], c[1] - b[1])
        ca = math.hypot(a[0] - c[0], a[1] - c[1])
        if ab == 0.0 or bc == 0.0 or ca == 0.0:
            continue
        area2 = abs((b[0] - a[0]) * (c[1] - a[1]) - (b[1] - a[1]) * (c[0] - a[0]))
        out[i] = 2.0 * area2 / (ab * bc * ca)   # 1/R = 4*Area/(abc)
    return out


def widths_from_curvature(kappas, w0, w1, r_narrow, r_wide):
    """Ширина линейно по кривизне: k<=1/r_narrow -> w0, k>=1/r_wide -> w1."""
    k0, k1 = 1.0 / r_narrow, 1.0 / r_wide
    out = []
    for k in kappas:
        t = (k - k0) / (k1 - k0)
        t = 0.0 if t < 0.0 else 1.0 if t > 1.0 else t
        out.append(w0 + (w1 - w0) * t)
    return out


def _unit(dx, dy):
    L = math.hypot(dx, dy)
    return (dx / L, dy / L) if L > 0 else (0.0, 0.0)


def _dir_back(pts, k, span):
    """Единичное направление по последним span метрам, заканчивающимся в pts[k]."""
    j = k
    while j > 0 and math.hypot(pts[k][0] - pts[j][0], pts[k][1] - pts[j][1]) < span:
        j -= 1
    return _unit(pts[k][0] - pts[j][0], pts[k][1] - pts[j][1]), j


def _dir_fwd(pts, k, span):
    j = k
    n = len(pts)
    while j < n - 1 and math.hypot(pts[j][0] - pts[k][0], pts[j][1] - pts[k][1]) < span:
        j += 1
    return _unit(pts[j][0] - pts[k][0], pts[j][1] - pts[k][1]), j


def detect_jumps(pts, thresh, z_thresh, span=4.0):
    """Ищет разрывы GNSS-решения на ломаной.

    Для каждого длинного отрезка k->k+1 сравнивает его с гипотезой "машина ехала по
    дуге": по направлениям до (d0) и после (d1) отрезка ожидаемое боковое смещение
    c_exp = a * tan(dtheta/2). Если фактическое боковое смещение отличается больше
    thresh, либо отрезок идёт назад, либо высота прыгает -- это разрыв.
    Возвращает список (k, (re, rn, ru)): невязка, которую надо сшить перед точкой k.
    """
    out = []
    n = len(pts)
    for k in range(n - 1):
        ve = pts[k + 1][0] - pts[k][0]
        vn = pts[k + 1][1] - pts[k][1]
        L = math.hypot(ve, vn)
        (d0e, d0n), j0 = _dir_back(pts, k, span)
        (d1e, d1n), j1 = _dir_fwd(pts, k + 1, span)
        if (d0e, d0n) == (0.0, 0.0) or (d1e, d1n) == (0.0, 0.0):
            continue
        r_lat = r_along = 0.0
        if L >= thresh * 0.5:                  # боковой разрыв ищем только на длинных отрезках
            a = ve * d0e + vn * d0n            # вдоль
            c = d0e * vn - d0n * ve            # поперёк (влево > 0)
            dtheta = math.atan2(d0e * d1n - d0n * d1e, d0e * d1e + d0n * d1n)
            if abs(dtheta) < math.radians(150):
                c_exp = a * math.tan(dtheta / 2.0)
            else:
                c_exp = c
            r_lat = c - c_exp
            r_along = a if a < 0 else 0.0      # движение назад -- тоже разрыв
        # высота: скачок, если перепад больше, чем возможно при уклоне MAX_GRADE
        dz = pts[k + 1][2] - pts[k][2]
        back = math.hypot(pts[k][0] - pts[j0][0], pts[k][1] - pts[j0][1])
        slope = (pts[k][2] - pts[j0][2]) / back if back > 0 else 0.0
        slope = max(-MAX_GRADE, min(MAX_GRADE, slope))
        z_jump = abs(dz) - MAX_GRADE * L > z_thresh
        r_z = dz - slope * L if z_jump else 0.0
        if abs(r_lat) > thresh or r_along < -thresh * 0.5 or z_jump:
            if abs(r_lat) <= thresh and r_along >= -thresh * 0.5:
                r_lat = 0.0
            re = r_lat * (-d0n) + r_along * d0e
            rn = r_lat * d0e + r_along * d0n
            out.append((k, (re, rn, r_z)))
    return out


def flatten_z_drift(pts, z_thresh, window=10.0, max_run=30.0, walk_back=15.0):
    """Дрейф/глитч высоты.

    Точка плохая, если её высота отличается от хорошей точки window м позади
    больше, чем возможно при уклоне MAX_GRADE (+ z_thresh). Начало плохого
    участка отматывается назад до точки, от которой набег ещё правдоподобен.
    Участок держится на высоте опорной точки, пока высота не вернётся к ней
    (глитч исчезает) или пока не пройдено max_run м -- тогда набег превращается
    в одну ступеньку в конце участка, её сшивает fix_jumps.
    Возвращает (pts, число исправленных точек).
    """
    n = len(pts)
    if n < 3:
        return list(pts), 0
    s = [0.0]
    for p, q in zip(pts, pts[1:]):
        s.append(s[-1] + math.hypot(q[0] - p[0], q[1] - p[1]))

    def deviates(i, a, extra=z_thresh):
        return abs(pts[i][2] - pts[a][2]) > MAX_GRADE * (s[i] - s[a]) + extra

    pts = list(pts)
    fixed = 0
    good = [0]          # индексы принятых точек
    gi = 0              # указатель на опорную точку в good (>= window м позади)
    i = 1
    while i < n:
        while gi + 1 < len(good) and s[i] - s[good[gi + 1]] >= window:
            gi += 1
        ref = good[gi]
        if not deviates(i, ref):
            good.append(i)
            i += 1
            continue
        # начало участка: самая ранняя точка в пределах walk_back, от которой
        # набег к i всё ещё неправдоподобен
        a = good[-1]
        for j in good:
            if s[i] - s[j] <= walk_back:
                if deviates(i, j, 0.5 * z_thresh):
                    a = j
                break
        j = len(good) - 1
        while j >= 0 and good[j] > a:
            j -= 1
        del good[j + 1:]
        gi = min(gi, len(good) - 1)
        b = i
        while b + 1 < n and s[b + 1] - s[a] <= max_run and deviates(b + 1, a):
            b += 1
        z0 = pts[a][2]
        for k in range(a + 1, b + 1):
            pts[k] = (pts[k][0], pts[k][1], z0)
            fixed += 1
        # b+1 -- новая опорная точка (новый "кадр"), сама не проверяется
        if b + 1 < n:
            good.append(b + 1)
        i = b + 2
    return pts, fixed


def fix_jumps(pts, thresh, z_thresh, blend, blend_z, glitch):
    """Убирает разрывы GNSS: короткие глитчи вырезает, остальные плавно сшивает.

    Сшивка: невязка r отрезка k->k+1 линейно "размазывается" по точкам до k
    (полностью в точке k, ноль на расстоянии blend м назад по дуге). Кадр после
    разрыва считается опорным.
    """
    pts = list(pts)
    if len(pts) < 3:
        return pts, 0, 0
    pts, n_drift = flatten_z_drift(pts, z_thresh)
    jumps = detect_jumps(pts, thresh, z_thresh)
    # --- глитчи: пара скачков с почти противоположной невязкой на коротком куске
    s = [0.0]
    for p, q in zip(pts, pts[1:]):
        s.append(s[-1] + math.hypot(q[0] - p[0], q[1] - p[1]))
    kill = set()
    used = set()
    def cancels(a, b, thr):
        """Компонента a и b противоположны: сумма заметно меньше большей из них."""
        big = max(abs(a), abs(b))
        return big > thr and abs(a + b) < 0.5 * big

    for i, (k1, r1) in enumerate(jumps):
        if i in used:
            continue
        for j in range(i + 1, len(jumps)):
            k2, r2 = jumps[j]
            if s[k2] - s[k1] > glitch:
                break
            h1 = math.hypot(r1[0], r1[1])
            h2 = math.hypot(r2[0], r2[1])
            dot = r1[0] * r2[0] + r1[1] * r2[1]
            lat_cancel = h1 > thresh and h2 > thresh and dot < 0 and \
                math.hypot(r1[0] + r2[0], r1[1] + r2[1]) < 0.5 * max(h1, h2)
            if cancels(r1[2], r2[2], z_thresh) or lat_cancel:
                kill.update(range(k1 + 1, k2 + 1))
                used.update((i, j))
                break
    n_glitch = len(kill)
    if kill:
        pts = [p for i, p in enumerate(pts) if i not in kill]
        jumps = detect_jumps(pts, thresh, z_thresh)
        s = [0.0]
        for p, q in zip(pts, pts[1:]):
            s.append(s[-1] + math.hypot(q[0] - p[0], q[1] - p[1]))
    # --- сшивка
    for k, (re, rn, ru) in jumps:
        i = k
        while i >= 0:
            d = s[k] - s[i]
            if d >= blend and d >= blend_z:
                break
            w = max(0.0, 1.0 - d / blend)
            wz = max(0.0, 1.0 - d / blend_z)
            e, n, u = pts[i]
            pts[i] = (e + re * w, n + rn * w, u + ru * wz)
            i -= 1
    return pts, len(jumps), n_glitch, n_drift


def prepare_road(pts, args):
    """Сшить разрывы, пересэмплировать, сгладить, посчитать ширину.
    -> (pts, widths, kappas, stats)"""
    pts, n_jumps, n_glitch, n_drift = fix_jumps(pts, args.jump, args.jump_z,
                                                args.jump_blend, args.jump_blend_z, args.glitch)
    pts = resample(pts, args.step)
    win = int(round(args.smooth / args.step)) | 1 if args.smooth > 0 else 1
    winz = int(round(args.smooth_z / args.step)) | 1 if args.smooth_z > 0 else 1
    xy = moving_average([(p[0], p[1]) for p in pts], win)
    z = moving_average([p[2] for p in pts], winz)
    pts = [(a, b, c) for (a, b), c in zip(xy, z)]
    kappas = curvatures(pts, int(round(args.curv_span / args.step)))
    widths = widths_from_curvature(kappas, args.width, args.width_max,
                                   args.r_narrow, args.r_wide)
    wwin = int(round(args.width_smooth / args.step)) | 1 if args.width_smooth > 0 else 1
    widths = moving_average(widths, wwin)
    return pts, widths, kappas, {'jumps': n_jumps, 'glitch_pts': n_glitch, 'drift_pts': n_drift}


def strip_edges(pts, widths, miter_limit=2.0, inner_clamp=0.9):
    """Левая и правая кромки ленты. -> (left, right, n_clamped)

    Смещение по биссектрисе (miter). На внутренней стороне поворота смещение
    ограничивается долей локального радиуса, чтобы кромка не выворачивалась.
    """
    n = len(pts)
    dirs, lens = [], []
    for (e0, n0, _), (e1, n1, _) in zip(pts, pts[1:]):
        de, dn = e1 - e0, n1 - n0
        L = math.hypot(de, dn)
        lens.append(L)
        dirs.append((de / L, dn / L) if L > 0 else (0.0, 0.0))
    left, right = [], []
    clamped = 0
    for i, (e, nn, u) in enumerate(pts):
        hl = hr = widths[i] / 2.0
        if i == 0 or i == n - 1:
            de, dn = dirs[0] if i == 0 else dirs[-1]
            scale = 1.0
        else:
            d0, d1 = dirs[i - 1], dirs[i]
            de, dn = d0[0] + d1[0], d0[1] + d1[1]
            L = math.hypot(de, dn)
            if L < 1e-9:                       # разворот на 180
                de, dn = d0
                scale = 1.0
            else:
                de, dn = de / L, dn / L
                cos_half = de * d1[0] + dn * d1[1]
                scale = min(miter_limit, 1.0 / max(cos_half, 1e-6))
                cross = d0[0] * d1[1] - d0[1] * d1[0]
                sin_half = math.sqrt(max(0.0, 1.0 - cos_half * cos_half))
                if sin_half > 1e-6:
                    r_loc = min(lens[i - 1], lens[i]) / (2.0 * sin_half)
                    lim = inner_clamp * r_loc / scale
                    if cross > 0 and hl > lim:      # левый поворот: внутри слева
                        hl = lim
                        clamped += 1
                    elif cross < 0 and hr > lim:
                        hr = lim
                        clamped += 1
        le, ln = -dn * scale, de * scale
        left.append((e + le * hl, nn + ln * hl, u))
        right.append((e - le * hr, nn - ln * hr, u))
    return left, right, clamped


def write_road_strip(f, pts, widths, z_up):
    """Связная лента: общие вершины на стыках, один квад на шаг."""
    f.write('o road\n')
    n = len(pts)
    if n < 2:
        return 0, 0
    left, right, clamped = strip_edges(pts, widths)
    for lp, rp in zip(left, right):
        for e, nn, u in (lp, rp):
            x, y, z = enu_to_obj(e, nn, u, z_up)
            f.write('v %s %s %s\n' % (fmt(x), fmt(y), fmt(z)))
    faces = 0
    for i in range(n - 1):
        a = 2 * i + 1        # left i
        b = 2 * i + 2        # right i
        c = 2 * i + 4        # right i+1
        d = 2 * i + 3        # left i+1
        f.write('f %d %d %d %d\n' % (a, b, c, d))
        faces += 1
    return faces, clamped


# --------------------------------------------------------------------------- #
# main
# --------------------------------------------------------------------------- #

def output_name(src, mode, width, outdir):
    stem = os.path.splitext(os.path.basename(src))[0]
    if mode == 'waypoints':
        suffix = 'waypoints'
    else:
        suffix = 'road%d' % round(width * 10)   # 3.5 -> road35
    return os.path.join(outdir or os.path.dirname(src) or '.', '%s-%s.obj' % (stem, suffix))


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('gpx', nargs='+', help='входные GPX-файлы')
    ap.add_argument('--mode', choices=['waypoints', 'road'], required=True)
    ap.add_argument('--lat0', type=float, default=LAT0, help='широта центра (default %(default)s)')
    ap.add_argument('--lon0', type=float, default=LON0, help='долгота центра (default %(default)s)')
    ap.add_argument('--ele-offset', type=float, default=0.0,
                    help='вычесть из высоты (по умолчанию высота абсолютная)')
    ap.add_argument('--width', type=float, default=WIDTH,
                    help='ширина дороги на прямой, м (default %(default)s)')
    ap.add_argument('--width-max', type=float, default=WIDTH_MAX,
                    help='ширина в самом крутом повороте, м (default %(default)s)')
    ap.add_argument('--r-narrow', type=float, default=R_NARROW,
                    help='радиус, от которого уширения уже нет, м (default %(default)s)')
    ap.add_argument('--r-wide', type=float, default=R_WIDE,
                    help='радиус, при котором ширина = --width-max, м (default %(default)s)')
    ap.add_argument('--step', type=float, default=STEP,
                    help='road: шаг пересэмплирования трека, м (default %(default)s)')
    ap.add_argument('--smooth', type=float, default=SMOOTH,
                    help='road: окно сглаживания геометрии, м (default %(default)s)')
    ap.add_argument('--curv-span', type=float, default=CURV_SPAN,
                    help='road: плечо оценки радиуса кривизны, м (default %(default)s)')
    ap.add_argument('--width-smooth', type=float, default=WIDTH_SMOOTH,
                    help='road: окно сглаживания ширины / длина отгона, м (default %(default)s)')
    ap.add_argument('--smooth-z', type=float, default=SMOOTH_Z,
                    help='road: окно сглаживания высоты, м (default %(default)s)')
    ap.add_argument('--jump', type=float, default=JUMP,
                    help='road: порог бокового скачка GNSS, м (default %(default)s)')
    ap.add_argument('--jump-z', type=float, default=JUMP_Z,
                    help='road: порог скачка высоты, м (default %(default)s)')
    ap.add_argument('--jump-blend', type=float, default=JUMP_BLEND,
                    help='road: длина сшивки бокового скачка, м (default %(default)s)')
    ap.add_argument('--jump-blend-z', type=float, default=JUMP_BLEND_Z,
                    help='road: длина сшивки скачка высоты, м (default %(default)s)')
    ap.add_argument('--glitch', type=float, default=GLITCH,
                    help='road: макс. длина глитча (скачок туда-обратно), который вырезается, м '
                         '(default %(default)s)')
    ap.add_argument('--min-step', type=float, default=None,
                    help='выкидывать подряд идущие точки ближе этого расстояния, м '
                         '(default: 0 для waypoints, 0.2 для road)')
    ap.add_argument('--rects', action='store_true',
                    help='road: независимые прямоугольники по сырым точкам вместо непрерывной ленты '
                         '(без уширения и сглаживания)')
    ap.add_argument('--polyline', action='store_true',
                    help='waypoints: добавить ломаную `l` через все точки')
    ap.add_argument('--z-up', action='store_true', help='оси X=восток Y=север Z=вверх')
    ap.add_argument('-o', '--outdir', default=None, help='каталог для .obj (default: рядом с gpx)')
    args = ap.parse_args(argv)

    if args.min_step is None:
        args.min_step = 0.0 if args.mode == 'waypoints' else 0.2

    proj = FlatProjection(args.lat0, args.lon0, args.ele_offset)
    if args.outdir:
        os.makedirs(args.outdir, exist_ok=True)

    for src in args.gpx:
        raw = read_gpx(src)
        if not raw:
            print('%s: нет trkpt, пропускаю' % src, file=sys.stderr)
            continue
        enu = [proj.to_enu(*p) for p in raw]
        pts = dedupe(enu, args.min_step)
        dst = output_name(src, args.mode, args.width, args.outdir)
        with open(dst, 'w') as f:
            write_header(f, src, args.mode, proj, args, len(raw), len(pts))
            if args.mode == 'waypoints':
                write_waypoints(f, pts, args.z_up, args.polyline)
                info = '%d points' % len(pts)
            else:
                if args.rects:
                    faces = write_road_rects(f, pts, args.width, args.z_up)
                    info = '%d points, %d quads (rects)' % (len(pts), faces)
                else:
                    rpts, widths, kappas, st = prepare_road(pts, args)
                    faces, clamped = write_road_strip(f, rpts, widths, args.z_up)
                    kmax = max(kappas) if kappas else 0.0
                    rmin = 1.0 / kmax if kmax > 0 else float('inf')
                    n_wide = sum(1 for w in widths if w > args.width + 0.05)
                    info = ('%d quads, width %.2f..%.2f m, min R %.0f m, widened %d of %d m, '
                            'jumps blended %d, glitch pts cut %d, z-drift pts %d, inner clamps %d'
                            % (faces, min(widths), max(widths), rmin,
                               round(n_wide * args.step), round(len(rpts) * args.step),
                               st['jumps'], st['glitch_pts'], st['drift_pts'], clamped))
        print('%s -> %s  (%s)' % (os.path.basename(src), os.path.basename(dst), info))


if __name__ == '__main__':
    main()
